version: '3.8'
services:
  mongo:
    container_name: adn_greenpeace_mongo_dist
    image: mongo:4
    restart: always
    volumes:
      - ./_shared_volume/db/:/data/db/
    ports:
      - "27018:27017"
