version: '3'
services:
  adn_greenpeace_client:
    container_name: adn_greenpeace_client
    image: adn_greenpeace_client:dev
    build:
      context: ./adn-greenpeace-client
      dockerfile: Dockerfile-dev
    ports:
      - "5053:3000"
    stdin_open: true
    volumes:
      - ./adn-greenpeace-client/:/usr/src/app/
      - /usr/src/app/node_modules
  mongo:
    container_name: adn_greenpeace_mongo
    image: mongo:4
    restart: always
    volumes:
      - ./_shared_volume/db/:/data/db/
    ports:
      - "27018:27017"
